spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOSTNAME}
      port: 27017
      username: springapp
      password: mongodb@123
      database: users
      authentication-database: admin

server:
  port: 8080
